
spring:
  datasource:
    url: jdbc:postgresql://dpg-d2v51fvfte5s73bo72qg-a:5432/portfolio_db_d7ks?sslmode=require
    username: admin_portfolio
    password: 37gASUoIR7g1EKokXK1rUd5UObo3MunH
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: ${PORT:8080}