spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/professionnel
    username: postgres
    password: passer
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
