

spring:
  datasource:
    url: jdbc:postgresql://db.sqwnjkfhmoefygqihyym.supabase.co:5432/postgres
    username: postgres
    password: Adiallo98@1   # remplace par ton vrai mot de passe
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update   # ou create-drop si tu veux recréer les tables à chaque test
    show-sql: true
