spring:
  datasource:
    url: jdbc:postgresql://dpg-d2v51fvfte5s73bo72qg-a:5432/portfolio_db_d7ks
    username: admin_portfolio
    password: 37gASUoIR7g1EKokXK1rUd5UO
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

logging:
  level:
    org.hibernate.SQL: DEBUG
    com.zaxxer.hikari: DEBUG
    org.springframework.jdbc: DEBUG
