spring:
  datasource:
    url: jdbc:postgresql://aws-1-eu-west-3.pooler.supabase.com:6543/postgres
    username: postgres.sqwnjkfhmoefygqihyym
    password: Adiallo98@1
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
